### ISSUE TITLE
Group management is broken

### ISSUE THREAD

**Issue by lockywolf** [Kitware/CDash#1268] opened 2022-09-04 05:47 UTC
I used to be able to open the Group Management page normally, until today.

Today I created a group manually, assigned one wildcard rule to it (basically, Model=Continuous), and tried to submit a build.

From now on when I am trying tto open the "manage groups" page, it looks like this:

![image](https://user-images.githubusercontent.com/2077025/188299419-c705d788-1e04-4c42-b7f1-9ee1a91d3ac2.png)

And the "project" dropdown list is empty. Any suggestions on how to fix it are welcome.

UPD1:
The logs have an error report:
```
192.168.2.10 - - [04/Sep/2022:05:52:47 +0000] "GET /manageBuildGroup.php?projectid=1 HTTP/1.0" 200 20377                                
[2022-09-04 05:52:47] development.ERROR: Trying to access array offset on value of type bool {"userId":1,"exception":"[object] (ErrorExc
eption(code: 0): Trying to access array offset on value of type bool at /home/kitware/cdash/app/cdash/app/Model/Site.php:240)           
[stacktrace]                                                                                                                            
#0 /home/kitware/cdash/app/cdash/app/Model/Site.php(240): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to
 acces...', '/home/kitware/c...', 240, Array)                                                                                           
#1 /home/kitware/cdash/app/cdash/app/Model/Site.php(219): CDash\\Model\\Site->Fill()                                                    
#2 /home/kitware/cdash/app/cdash/public/api/v1/manageBuildGroup.php(185): CDash\\Model\\Site->GetName()                                 
#3 /home/kitware/cdash/app/Http/Controllers/CDash.php(164): require('/home/kitware/c...')                                               
#4 /home/kitware/cdash/app/Http/Controllers/CDash.php(182): App\\Http\\Controllers\\CDash->getRequestContents()                         
#5 /home/kitware/cdash/app/Http/Controllers/CDash.php(55): App\\Http\\Controllers\\CDash->handleApiRequest()                            
#6 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\CDash->__invoke(Objec
t(Illuminate\\Http\\Request), 'api/v1/manageBu...')                                                                                     
#7 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->ca
llAction('__invoke', Array)                                                                                                             
#8 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispat
ch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CDash), '__invoke')                                               
#9 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()      
#10 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()              
#11 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Rou
ting\\{closure}(Object(Illuminate\\Http\\Request))                         
#12 /home/kitware/cdash/app/Http/Middleware/CheckPassword.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Objec
t(Illuminate\\Http\\Request))                                                                                                           
#13 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckPassword->handle
(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pip
eline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteB
indings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline
\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\Ve
rifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pi
peline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFro
mSession->handle(Object(Illuminate\\Http\\Request), Object(Closure)) 
#20 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline-
>Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSessio
n->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeli
ne\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCoo
kiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline
->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request)) 
#25 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCooki
es->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\
Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Clo
sure))
#28 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStac
k(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Il
luminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#30 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Ob
ject(Illuminate\\Http\\Request))
#31 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(O
bject(Illuminate\\Http\\Request))
#32 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illumi
nate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request)) 
#33 /home/kitware/cdash/app/Http/Middleware/CheckDirectoryPermissions.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{cl
osure}(Object(Illuminate\\Http\\Request))
#34 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDirectoryPermiss
ions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/kitware/cdash/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}
(Object(Illuminate\\Http\\Request))
#36 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Objec
t(Illuminate\\Http\\Request), Object(Closure))
#37 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeli
ne\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\Tr
ansformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeli
ne\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\Tr
ansformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/kitware/cdash/app/Http/Middleware/CheckDatabaseConnection.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{clos
ure}(Object(Illuminate\\Http\\Request))
#42 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckDatabaseConnecti
on->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\
Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\Ch
eckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\
Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Ob
ject(Closure))
#47 /home/kitware/cdash/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->s
endRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 /home/kitware/cdash/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"} 
192.168.2.10 - - [04/Sep/2022:05:52:47 +0000] "GET /api/v1/manageBuildGroup.php?projectid=1 HTTP/1.0" 500 1162
```

**Comment by williamjallen** [comment] 2023-04-18 19:46
This appears to be a duplicate of https://github.com/Kitware/CDash/issues/1291.  Since the other issue has more information about the problem, I am closing this one.

**Closed by williamjallen** 2023-04-18 19:46 UTC
