### ISSUE TITLE
Submission of "Done" step no longer closes a build

### ISSUE THREAD

**Issue by bradking** [Kitware/CDash#1603] opened 2023-07-26 14:07 UTC
# Bug report

### Expected Behavior

When CTest submits `Done.xml` for a build, that build should be closed so that further submissions refresh it rather than appending.

### Actual Behavior

CTest submits `Done.xml` but the build remains open and further submissions append.

### CDash Version

This problem started on `open.cdash.org` after the recent update.  It is currently running version 3.1.0-442-g6e68ccc9e.

**Comment by zackgalbreath** [comment] 2023-07-31 15:59
Thanks for reporting this.

Looking at the CMake builds for today (2023-07-31) I can see that only 16 of 338 (~5%) are marked as "done".

Here's the list of builds that _did_ get marked as done. Do you happen to know if there's anything special/different about these? I'm trying to figure out if this is a problem is due to a race condition during asychronous submission or something else.

FWIW, minimal reproducers do seem to get marked as done, at least in my manual testing.


```
+--------------------------------------------+--------------------------------+
| buildname                                  | sitename                       |
+--------------------------------------------+--------------------------------+
| vs12-64-ide                                | vesper.kitware                 |
| MacOSX10.5.8-gmake-g++-mp-4.7              | claus-kleins-macbook-pro.local |
| linux-make                                 | minoc.kitware                  |
| vs16-64-ide                                | terfin.kitware                 |
| cmake-hip5.5_radeon                        | gitlab-ci                      |
| cmake-cuda10.2_nvidia                      | gitlab-ci                      |
| cmake-hip5.5_radeon                        | gitlab-ci                      |
| cmake-cuda9.2_nvidia                       | gitlab-ci                      |
| nightly-cmake-debian12_ninja_clang         | gitlab-ci                      |
| cmake-cuda10.2_nvidia                      | gitlab-ci                      |
| cmake-cuda10.2_clang                       | gitlab-ci                      |
| nightly-cmake-cuda9.2_nvidia               | gitlab-ci                      |
| nightly-cmake-windows_oneapi2023.1.0_ninja | gitlab-ci                      |
| cmake-cuda11.8_minimal_nvidia              | gitlab-ci                      |
| nightly-cmake-cuda10.2_nvidia              | gitlab-ci                      |
| nightly-cmake-cuda11.6_clang               | gitlab-ci                      |
+--------------------------------------------+--------------------------------+
```

**Comment by bradking** [comment] 2023-07-31 17:56
That list looks pretty random.  I suggest looking across a few days to see if there is any pattern.

**Closed** 2023-08-02 20:57 UTC
Labels: bug report
