### ISSUE TITLE
Error with docker-compose run --rm cdash install configure

### ISSUE THREAD

**Issue by willfern123** [Kitware/CDash#1348] opened 2023-04-07 20:40 UTC
Hey!

I'm working with WSL and I'm following the Docker instructions.

I ran:

git clone https://github.com/Kitware/CDash
cd CDash
docker-compose pull
docker-compose up -d cdash

and then:

docker-compose run --rm cdash install configure
gives me an error:

> webpack compiled successfully
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
> [Fri Apr 07 20:34:45.256652 2023] [mpm_prefork:notice] [pid 68] AH00163: Apache/2.4.56 (Debian) PHP/8.1.17 configured -- resuming normal operations
> [Fri Apr 07 20:34:45.256695 2023] [core:notice] [pid 68] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
> The environment file is invalid!
> Failed to parse dotenv file. Encountered unexpected whitespace at ['1';].
> 127.0.0.1 - - [07/Apr/2023:20:34:47 +0000] "POST /install.php HTTP/1.1" 500 211
> The environment file is invalid!
> Failed to parse dotenv file. Encountered unexpected whitespace at ['1';].
> 127.0.0.1 - - [07/Apr/2023:20:34:47 +0000] "POST /user.php HTTP/1.1" 500 211
> The environment file is invalid!
> Failed to parse dotenv file. Encountered unexpected whitespace at ['1';].
> 127.0.0.1 - - [07/Apr/2023:20:34:47 +0000] "POST /user.php HTTP/1.1" 500 211
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
> [Fri Apr 07 20:34:47.972660 2023] [mpm_prefork:notice] [pid 68] AH00170: caught SIGWINCH, shutting down gracefully

Currently I have the .env.example in the CDash project root. How do I configure the .env as needed?

**Comment by josephsnyder** [comment] 2023-04-10 14:24
@willfern123, thanks for bringing this to our attention and for finding this issue.  I can replicate it with the current set of images we provide.  This isn't an issue with your set of configuration updates but something that CDash sets when trying to set up the system for the `install configure` part of the entry point. 
The problem is likely here where we write into the config file, https://github.com/Kitware/CDash/blob/master/docker/bash/misc.bash#L31.  It it still uses the `php` syntax with a `;` at the end of the line which will trip up the dotenv parser.

It relates to #1336 but isn't a place covered by the string replacement that we added. I'll push a PR with this fix.

**Comment by willfern123** [comment] 2023-04-10 15:23
Thanks for the fix! I'm now logged into my profile:

![image](https://user-images.githubusercontent.com/130184717/230931678-6b1b71c0-74e8-4ae1-9262-a03434f29a44.png)

I don't see where to create a new project, though.

**Comment by josephsnyder** [comment] 2023-04-10 15:37
You need to be an administrator to create new projects on each CDash instance. 

Your best bet is to sign in as the administrator of the instance and create the project if its one-time event.   You can also use the "Manage users" page in the Admin page to elevate your "William" account to an administrator if you need to create projects more often. 

If you didn't change either of the "CDASH_ROOT_ADMIN_EMAIL" or "CDASH_ROOT_ADMIN_PASS" values when setting the system up, the default administrator account information is `root@docker.container` and `secret`.

**Comment by josephsnyder** [comment] 2023-04-13 12:10
Closing issue as fixed by #1349.

**Closed by josephsnyder** 2023-04-13 12:10 UTC
