### ISSUE TITLE
Clicking on MyCDash results in error

### ISSUE THREAD

**Issue by bobby-philip** [Kitware/CDash#1151] opened 2021-05-24 18:18 UTC
*/ define('LARAVEL_START', microtime(true)); /* |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provides a convenient, automatically generated class loader for | our application. We just need to utilize it! We'll simply require it | into the script here so that we don't have to worry about manual | loading any of our classes later on. It feels great to relax. | */ require __DIR__.'/../vendor/autoload.php'; /* |-------------------------------------------------------------------------- | Turn On The Lights |-------------------------------------------------------------------------- | | We need to illuminate PHP development, so let us turn on the lights. | This bootstraps the framework and gets it ready for use, then it | will load up this application so that we can run it and send | the responses back to the browser and delight our users. | */ $app = require_once __DIR__.'/../bootstrap/app.php'; /* |-------------------------------------------------------------------------- | Run The Application |-------------------------------------------------------------------------- | | Once we have the application, we can handle the incoming request | through the kernel, and send the associated response back to | the client's browser allowing them to enjoy the creative | and wonderful application we have prepared for them. | */ $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response);

**Comment by williamjallen** [comment] 2023-04-18 18:57
This is likely due to a CDash misconfiguration on your instance.  This isn't happening for me with the latest changes and the issue isn't clear enough to point to a potential problem, so I'll close the issue given that this issue is several years old at this point.

**Closed by williamjallen** 2023-04-18 18:57 UTC
