### ISSUE TITLE
Build start time offset

### ISSUE THREAD

**Issue by sjoubert** [Kitware/CDash#628] opened 2018-01-30 11:46 UTC
I have an issue with some builds on my own instance of CDash (both v2.4.0-prebuilt and prebuilt_1e075408b6395bc97611b4d1845c8173fef32c37). However I'm not sure if it's a CDash issue or a build client one.

Basically, the reported start time of some, but not all, of the submitted builds are off by 1 hour. The individual time of the steps (update, configure,...) are correct but the tool tip in the start time column reports a start time off by 1 hour (before the expected time) and a total build time of 1 hour more than the reality. I don't know if the 1 hour offset is fixed or due to the fact that my current timezone is CET (UTC+1)

I've checked and all the involved machine have the same timezone:
* The CDash server and all the client build machines (both the ones that are correct and the odd ones) are set to Europe/Paris (currently CET)
* The CDash server config (config.local.php) has been set to Europe/Paris and the displayed time in the interface is correct
* I've checked the submitted XML and all of them are correct. The timestamp is correct and the timezoned start time indicates "CET"

I'm a bit lost as what could cause this issue. A bug server-side would probably result in an error on every submissions, but some of them are fine. And I cannot find what subtle difference there can be on the build clients.

Any ideas?

**Comment by sjoubert** [comment] 2018-01-30 14:01
Maybe this is related to #579

**Comment by zackgalbreath** [comment] 2018-01-30 15:21
Thanks for the report.  Off the top of my head, I'm not sure what's going wrong here.  Could you provide us with a small set of XML files that reproduces this problem for you?

**Comment by sjoubert** [comment] 2018-03-14 09:12
Well, apparently a few days ago the submission that were ok started to have the offset too. At least now, all submissions are consistent. In the mean they were update on those computers, unfortunately I can't tell exactly what or if it may have trigger the behavior switch.

I'll try to reduce the data to a minimal reproducible test case, but this is not easy.

**Comment by zackgalbreath** [comment] 2018-03-14 13:57
If it just started acting up again a couple of days ago then it is probably due to a problem with Daylight Saving Time.

**Comment by sjoubert** [comment] 2018-03-14 15:48
I thought it might but some of the submission were already "broken" this winter.

I tried to apply bc344f9b329c188b1eaeafb369760c1d44c6811c without any effect.
* Does this fix takes immediately effect or do I have to wait for new submission?
* Any other commits I might try related to that subject?

**Comment by zackgalbreath** [comment] 2018-03-22 14:24
> I'll try to reduce the data to a minimal reproducible test case, but this is not easy.

If you notice this problem happen again, try to grab the XML files that were produced by the offending build.  For the most part, CTest and CDash now use Unix timestamps (integers) to indicate when each phase of the build started and stopped.  If we can identify what values in the XML files are causing this issue I bet we'll be able to fix it.

**Comment by sjoubert** [comment] 2018-03-23 13:05
The files are submitted separately after each step of my ctest script in that order:
* Notes then Update
* Configure
* Build
* Test

While grabbing these files and redacting personal data I've noticed that the `Time` element of the Notes file is a floating point which may be of interest in this matter:
`<Time>1.52175e+09</Time>`
I've tested without submitting the Notes.xml and the offset is fixed. This is also consistent with the observation of some of my builds starting to behave wrongly. Well, I just added some notes of these ones a few day ago.

As a workaround on my side, I've modified my ctest script to submit the Notes after the Update and it works fine.

So, in the end the problem seems to be in the ctest generation of the XML file. I'm closing this and will open an issue on the CMake/CTest bug tracker or a MR if I can quickly find a fix myself. I'll link that here.

Thanks a lot for the help!

**Comment by sjoubert** [comment] 2018-03-23 13:28
On second thoughts, I'll reopen this and let you close it if you consider there are no action on the CDash side. Maybe you'll want to add some error management to reject submission with invalid timestamp (or accept floating point value but I doubt that)

**Comment by zackgalbreath** [comment] 2018-03-23 13:57
> Thanks a lot for the help!

You're welcome!  I actually already fixed this bug in CTest: https://gitlab.kitware.com/cmake/cmake/merge_requests/1428

This fix will be included in the upcoming v3.11.0 release of CMake.

**Closed** 2018-03-23 13:57 UTC
