### ISSUE TITLE
After 3.2.3 to 3.4.2 upgrade, "My CDash" page is mostly broken, links have incorrect `undefined` within them

### ISSUE THREAD

**Issue by seanm** [Kitware/CDash#2272] opened 2024-06-14 20:55 UTC
Today we upgraded from 3.2.3 to 3.4.2 and after doing some testing, noticed that the "My CDash" page is mostly broken.

- the logo at the top left is missing the graphic and replaced with the word Logo
- all the links have `undefined` in them. ex `https://cdash.rogue-research.com/undefined/index.php?project=Shared` and going there gives 404. Editing the URL to remove the `undefined` gives a working URL.

<img width="1029" alt="CDash3 4 2" src="https://github.com/Kitware/CDash/assets/117260/e7f82180-511d-400a-9526-42bf87ff2174">

**Comment by williamjallen** [comment] 2024-06-15 00:04
Are there any errors in the console?

**Comment by seanm** [comment] 2024-06-17 16:23
@williamjallen we don't see anything interesting/relevant in the apache logs. (except maybe `PHP Fatal error:  Allowed memory size of 1048576000 bytes exhausted (tried to allocate 970384313 bytes)` but we saw those before the upgrade too.)

But when you say "console" do you mean the web browser's debugging features? That's not a tool I've really used, but did see 3 things:

`Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead.`

`NotFoundError: No such JSProcessActor 'BrowserToolboxDevToolsProcess'`

`Cookie “cdash_session” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

**Comment by seanm** [comment] 2024-06-17 17:41
1. Yes.
2. No. Yes.

**Comment by williamjallen** [comment] 2024-06-17 18:22
I'm unable to reproduce this issue, and we haven't seen this issue with any other bare metal systems, so I'm going to close this as "can't reproduce" for now.

This feels like a misconfiguration issue of some sort, but it's hard to tell without more information.  The "undefined" is caused by the `APP_URL` not making it all the way to the UI somehow.  Another interesting thing to note is that the footer indicates CDash 3.4.0, not 3.4.2.

**Closed by williamjallen** 2024-06-17 18:22 UTC
Labels: bug report

**Comment by seanm** [comment] 2024-06-17 18:47
> This feels like a misconfiguration issue of some sort, but it's hard to tell without more information.

What other info can we provide?

>The "undefined" is caused by the `APP_URL` not making it all the way to the UI somehow.

Hmmm, Can some tracing be enabled to see where it gets lost?

>Another interesting thing to note is that the footer indicates CDash 3.4.0, not 3.4.2.

Yeah, that seems to be another bug:

https://github.com/Kitware/CDash/issues/1198#issuecomment-2168741258

**Comment by zackgalbreath** [comment] 2024-06-17 19:12
In your .env file, do you also have this line after `APP_URL` has been defined?

`MIX_APP_URL="${APP_URL}"`

**Comment by seanm** [comment] 2024-06-17 21:21
We did not, but adding it doesn't change anything. Does something need to be 'kicked' to re-read the .env file?  install.md sorta implies one should run `npm run production` again after touching .env?

**Comment by williamjallen** [comment] 2024-06-17 21:24
Yes, you need to run `npm run production` for `MIX_APP_URL` to be built into the UI.

**Comment by seanm** [comment] 2024-11-05 16:01
We just updated to 3.5.1 and this bug went away.
